%\VignetteIndexEntry{QCqPCR}                                       
%\VignetteDepends{stats,Biobase,methods,ReadqPCR}                            
%\VignetteKeywords{real-time, quantitative, PCR, quality control}
%\VignettePackage{QCqPCR}
%
\documentclass[11pt]{article}
\usepackage{geometry}\usepackage{color}
\definecolor{darkblue}{rgb}{0.0,0.0,0.75}
\usepackage[%
baseurl={http://qpcr.r-forge.r-project.org/},%
pdftitle={QCqPCR: Functions to assess the quality of qPCR data in R},%
pdfauthor={James Perkins},%
pdfsubject={QCqPCR},%
pdfkeywords={real-time, quantitative, PCR, qPCR, RT-qPCR, quality control},%
pagebackref,bookmarks,colorlinks,linkcolor=darkblue,citecolor=darkblue,%
pagecolor=darkblue,raiselinks,plainpages,pdftex]{hyperref}
%
\markboth{\sl Package ``{\tt QCqPCR}''}{\sl Package ``{\tt QCPCR}''}
%
% -------------------------------------------------------------------------------
\newcommand{\code}[1]{{\tt #1}}
\newcommand{\pkg}[1]{{\tt "#1"}}
\newcommand{\myinfig}[2]{%
%  \begin{figure}[htbp]
    \begin{center}
      \includegraphics[width = #1\textwidth]{#2}
%      \caption{\label{#1}#3}
    \end{center}
%  \end{figure}
}
% -------------------------------------------------------------------------------
%
% -------------------------------------------------------------------------------
\begin{document}
%\SweaveOpts{keep.source = TRUE, eval = TRUE, include = FALSE}
%-------------------------------------------------------------------------------
\title{QCqPCR: Functions to assess the quality of qPCR data in R}
%-------------------------------------------------------------------------------
\author{James Perkins\\
University College London\medskip\\
}
\maketitle
\tableofcontents
%-------------------------------------------------------------------------------
\section{Introduction}

There are a number of problems inherent with the technologies used by high throughput RT-qPCR systems, and also problems related to normalisation of the data, which apply to using RT-qPCR in general, and can apply to other technologies, such as metabolomics assays.
The former, technology related problem can lead to the presence of spatial effects and other systematic biases on the arrays.
The latter problems refers to problems related to chosing the optimal housekeeping genes for normalisation.
These are internal control genes that are chosen to normalise the samples because they are not expected to change in abundance between different tissues types being investigated, or in response to experimental treatments being applied.
\\
QCqPCR consists of a number of S4 methods that can be called on the qPCRBatch object described in \pkg{ReadqPCR}. The general way to call these methods is as: \code{<METHOD>(qPCRBatch, <other arguments seperated by `,'>)}. The methods output various things, such as correlation matrices and graphical plots, which can be used for the easy identification and quantification of problems in an experiment.


\section{Identifying spatial effects and other systematic bias}

\subsection{PseudoPlots}
The Pseudoplots method creates a pseudo-image of the different plates used in the experiment. For taqman files they will have a default layout of 24 x 16 Wells. This is a representation of the plate, with the spatial locations of the wells on the plate represented as circles. The colour of the circles will vary depending on what is being plotted. 
Currently one can plot raw Ct values, or residuals, depending on what the user wishes to identify.

The user must first read in their taqman file(s) using the \pkg{ReadqPCR} package. Here we show an example with a 2 plate experiment, with each plate consisting of 4 samples, with the same detectors. Each sample has the same order of detectors and takes up 4 consecutive rows on each plate. So for example the first sample will be all the columns in rows 1 - 4, the second sample all columns in 5-8, and so forth.

<<readTaqman, echo=TRUE, width=200, height=160, eval=TRUE>>=
library(ReadqPCR)
library(QCqPCR)
path <- system.file("exData", package = "ReadqPCR")
taqman.example <- paste(path, "/example.txt", sep="")
taqmanqPCRBatch <- read.taqman(taqman.example)
@

\subsubsection{Raw Ct Values}

Raw Ct values can be plotted to show obvious problems with the data. Undetermined values can be given a specified value, or a user defined cut-off can be used instead. This is mainly of use in order to find any detectors that arise too soon, or problematic channels. If the plate contains undertermined values, these will not be plotted.

<<PseudoPlotCtsNA, fig=TRUE, width = 200, height=200>>=
PseudoPlot(qPCRBatch=taqmanqPCRBatch)
@

The alternative way to deal with undertermined Ct values is to make a cutoff Ct value, and assign it to anything equal or above this value. Other ways of dealing with Undertermined Ct values are shown in the \pkg{NormqPCR} package. Here we show what happens with a cutoff of 38.

<<PseudoPlotCts, fig=TRUE, width = 200, height=200>>=
PseudoPlot(qPCRBatch=taqmanqPCRBatch, cutOff=38)
@

\subsubsection{Plot with average and residuals}

There are 3 further ways of plotting values back onto the chips, which involve calculating the average (mean or median) value for a plate/sample/well position and then plotting how the values deviate from the average, by plotting either the number of standard deviations, or MADs (median absolute deviations) from the calculated distance all of the Cts values are. 

The average can be the average Ct value for all wells on a given plate, as is the case when plotting plate residuals, calculated for the same position across the different plates, as is the case when plotting well residuals, or can be calculated for each of the detectors, which might be intra or inter-plate, depending on the experimental setup.

For plate residuals:
<<PseudoPlotPlate, fig=TRUE, width = 200, height=200>>=
PseudoPlot(qPCRBatch=taqmanqPCRBatch, plotType="Plate.Residuals", cutOff=38)
@
For well residuals:
<<PseudoPlotWell, fig=TRUE, width = 200, height=200>>=
PseudoPlot(qPCRBatch=taqmanqPCRBatch, plateToPlot="1", plotType="Well.Residuals", cutOff=38)
@
For detector residuals:
\subsubsection{Detector Residuals}
<<PseudoPlotDetector, fig=TRUE, width = 200, height=200>>=
PseudoPlot(qPCRBatch=taqmanqPCRBatch, plateToPlot="1", plotType="Detector.Residuals", cutOff=38)
@

\subsection{qPCRPairs}

Pairwise plots can be made between the different samples, or between different plates, in a similar way to the \code{pairs} function in the \code{graphics} package (in fact it calls this function directly after re-arranging the data).
The latter option will only be likely to produce sensible looking and  results when comparing plates with the same experimental setup.

\subsection{Pairs}

\section{Visual comparison of housekeeping gene performance}

SOMETHING ABOUT THIS
%-------------------------------------------------------------------------------
%

\end{document}
