%\VignetteIndexEntry{Functions to assess the quality of RT-qPCR data in R}                                       
%\VignetteDepends{stats,Biobase,methods,ReadqPCR}                            
%\VignetteKeywords{real-time, quantitative, RT-qPCR, qPCR, quality control}
%\VignettePackage{QCqPCR}
%
\documentclass[11pt]{article}
\usepackage{geometry}\usepackage{color}
\definecolor{darkblue}{rgb}{0.0,0.0,0.75}
\usepackage[%
baseurl={http://qpcr.r-forge.r-project.org/},%
pdftitle={QCqPCR: Functions to assess the quality of qPCR data in R},%
pdfauthor={James Perkins},%
pdfsubject={QCqPCR},%
pdfkeywords={real-time, quantitative, PCR, qPCR, RT-qPCR, quality control},%
pagebackref,bookmarks,colorlinks,linkcolor=darkblue,citecolor=darkblue,%
pagecolor=darkblue,raiselinks,plainpages,pdftex]{hyperref}
%
\markboth{\sl Package ``{\tt QCqPCR}''}{\sl Package ``{\tt QCPCR}''}
%
% -------------------------------------------------------------------------------
\newcommand{\code}[1]{{\tt #1}}
\newcommand{\pkg}[1]{{\tt "#1"}}
\newcommand{\myinfig}[2]{%
%  \begin{figure}[htbp]
    \begin{center}
      \includegraphics[width = #1\textwidth]{#2}
%      \caption{\label{#1}#3}
    \end{center}
%  \end{figure}
}
% -------------------------------------------------------------------------------
%
% -------------------------------------------------------------------------------
\begin{document}
%\SweaveOpts{keep.source = TRUE, eval = TRUE, include = FALSE}
%-------------------------------------------------------------------------------
\title{QCqPCR: Functions to assess the quality of RT-qPCR data in R}
%-------------------------------------------------------------------------------
\author{James Perkins\\
University College London\medskip\\
}
\maketitle
\tableofcontents
%-------------------------------------------------------------------------------
\section{Introduction}

There are a number of problems inherent with the technologies used by high throughput RT-qPCR systems, and also problems related to normalisation of the data, which apply to using RT-qPCR in general, and can apply to other technologies, such as metabolomics assays.

The former, technology related problem can lead to the presence of spatial effects and other systematic biases on the arrays.

The latter problems refers to problems related to chosing the optimal housekeeping genes for normalisation. These are internal control genes that are chosen to normalise the samples because they are not expected to change in abundance between different tissues types being investigated, or in response to experimental treatments being applied.

QCqPCR consists of a number of S4 methods that can be called on the qPCRBatch object described in \pkg{ReadqPCR}. They are documented in this vignette.
%-------------------------------------------------------------------------------
\section{Identifying spatial effects and other systematic bias}

\subsection{PseudoPlots}
The Pseudoplots method creates a pseudo-image of the different plates used in the experiment. Currently these only work for Taqman SDS output. They will therefore have a default layout of 24 x 16 Wells. This is a representation of the plate, with the spatial locations of the wells on the plate represented as circles. The colour of the circles will vary depending on what is being plotted.
Currently one can plot raw Ct values, or residuals, depending on what the user wishes to identify.

The user must first read in their taqman file(s) using the \pkg{ReadqPCR} package. Here we show an example with a 2 plate experiment, with each plate consisting of 4 samples, with the same detectors. Each sample has the same order of detectors and takes up 4 consecutive rows on each plate. So for example the first sample will be contained in rows 1 - 4, the second sample in 5-8, and so forth.

<<readTaqman, echo=TRUE, width=200, height=160, eval=TRUE>>=
library(ReadqPCR)
library(QCqPCR)
path <- system.file("exData", package = "NormqPCR")
taqman.example <- paste(path, "/example.txt", sep="")
taqman.qPCRBatch <- read.taqman(taqman.example)
@

\subsubsection{Raw Ct Values}

Raw Ct values can be plotted to show obvious problems with the data. Undetermined values can be given a specified value, or a user defined cut-off can be used instead. The plotting of raw, unnormalised Ct values is mainly of use in order to find any detectors that arise too soon, or any problematic channels. If the plate contains undetermined values, these will not be plotted, and a gap will appear

<<PseudoPlotCtsNA, fig=TRUE, width = 200, height=200>>=
PseudoPlot(qPCRBatch=taqman.qPCRBatch, plateToPlot="1")
@

The alternative way to deal with undetermined Ct values is to make a cutoff Ct value, and assign it to anything equal or above this value. Other ways of dealing with Undertermined Ct values are shown in the \pkg{NormqPCR} package. Here we show what happens with a cutoff of 38.

<<PseudoPlotCts, fig=TRUE, width = 200, height=200>>=
PseudoPlot(qPCRBatch=taqman.qPCRBatch,  plateToPlot="1", cutOff=38)
@

\subsubsection{Plot with average and residuals}

There are 3 further ways of plotting values back onto the chips, which involve calculating the average (mean or median) value for a plate/sample/well position and then plotting how the values deviate from the average, by plotting either the number of standard deviations, or MADs (median absolute deviations) from the calculated distance all of the Cts values are. 

The average can be the average Ct value for all wells on a given plate, as is the case when plotting plate residuals, calculated for the same position across the different plates, as is the case when plotting well residuals, or can be calculated for each of the detectors, which might be intra or inter-plate, depending on the experimental setup.

For plate residuals:
<<PseudoPlotPlate, width = 200, height=200>>=
#PseudoPlot(qPCRBatch=taqman.qPCRBatch, plotType="Plate.Residuals", cutOff=38)
#PseudoPlot(qPCRBatch=taqman.qPCRBatch, plotType="Plate.Residuals", cutOff=38, statType="non-parametric")
@
For well residuals:
<<PseudoPlotWell, width = 200, height=200>>=
#PseudoPlot(qPCRBatch=taqman.qPCRBatch, plateToPlot="1", plotType="Well.Residuals", cutOff=38)
#PseudoPlot(qPCRBatch=taqman.qPCRBatch, plateToPlot="1", plotType="Well.Residuals", cutOff=38, statType="non-parametric")
@
For detector residuals:
\subsubsection{Detector Residuals}
<<PseudoPlotDetector, width = 200, height=200>>=
#PseudoPlot(qPCRBatch=taqman.qPCRBatch, plateToPlot="1", plotType="Detector.Residuals", cutOff=38)
#PseudoPlot(qPCRBatch=taqman.qPCRBatch, plateToPlot="1", plotType="Detector.Residuals", cutOff=38, statType="non-parametric")
@
%-------------------------------------------------------------------------------
\section{Visual comparison of housekeeping gene performance}



SOMETHING ABOUT THIS
%-------------------------------------------------------------------------------
%

\end{document}
